#!/bin/bash

echo "🚀 Railway Deployment Script"
echo "============================"
echo

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "❌ Error: Not in a git repository"
    exit 1
fi

# Check if required files exist
if [ ! -f "AcademyAwards.json" ]; then
    echo "❌ Error: AcademyAwards.json not found"
    exit 1
fi

if [ ! -f "myDatabase.db" ]; then
    echo "📝 Database not found - will create new one"
    database_needs_update=true
else
    # Check if JSON is newer than database
    if [ "AcademyAwards.json" -nt "myDatabase.db" ]; then
        echo "🔄 AcademyAwards.json is newer than database"
        database_needs_update=true
    else
        database_needs_update=false
    fi
fi

# Update database if needed
if [ "$database_needs_update" = true ]; then
    echo
    echo "📊 Database Update Required"
    echo "=========================="
    
    # Show JSON info
    total_records=$(node -e "console.log(JSON.parse(require('fs').readFileSync('AcademyAwards.json', 'utf8')).length)")
    latest_year=$(node -e "const data = JSON.parse(require('fs').readFileSync('AcademyAwards.json', 'utf8')); console.log(Math.max(...data.map(d => parseInt(d.year))))")
    
    echo "📈 JSON file contains: $total_records records"
    echo "🗓️  Latest year: $latest_year"
    echo
    
    read -p "🔄 Update database with new awards data? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "🔧 Updating database..."
        node update-database.js
        
        if [ $? -eq 0 ]; then
            echo "✅ Database updated successfully!"
        else
            echo "❌ Database update failed!"
            exit 1
        fi
    else
        echo "⚠️  Database update skipped - proceeding with existing database"
    fi
    echo
fi

# Check for unstaged changes (including updated database)
if ! git diff-index --quiet HEAD --; then
    echo "⚠️  You have unstaged changes."
    
    # Show what changed
    changed_files=$(git diff --name-only HEAD)
    echo "📝 Changed files: $changed_files"
    
    if [ "$database_needs_update" = true ] && echo "$changed_files" | grep -q "myDatabase.db"; then
        # Auto-commit database updates with descriptive message
        echo "🤖 Auto-committing database update..."
        git add .
        
        commit_msg="Update awards database with latest data

- Updated database with $total_records total records
- Latest ceremony year: $latest_year
- Auto-generated by deploy script"
        
        git commit -m "$commit_msg"
        echo "✅ Database changes committed automatically"
    else
        # Manual commit for other changes
        read -p "Stage and commit them? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git add .
            read -p "Enter commit message: " commit_msg
            git commit -m "$commit_msg"
        else
            echo "❌ Deployment cancelled. Please commit your changes first."
            exit 1
        fi
    fi
fi

# Check for uncommitted staged changes
if ! git diff-index --cached --quiet HEAD --; then
    echo "⚠️  You have staged but uncommitted changes."
    read -p "Commit them? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        read -p "Enter commit message: " commit_msg
        git commit -m "$commit_msg"
    else
        echo "❌ Deployment cancelled. Please commit your staged changes first."
        exit 1
    fi
fi

# Deploy to Railway
if [ "$(git log origin/main..main 2>/dev/null)" != "" ] || ! git diff-index --quiet HEAD -- 2>/dev/null; then
    echo "📤 Pushing changes to GitHub..."
    git push origin main
    
    if [ $? -eq 0 ]; then
        echo "✅ Successfully pushed to GitHub!"
        echo
        echo "🎯 Railway will automatically deploy your changes."
        echo "🌐 Live URL: https://web-production-b8145.up.railway.app"
        echo "📊 Check deployment status at: https://railway.app"
        echo
        echo "⏱️  Deployment typically takes 1-2 minutes."
        
        if [ "$database_needs_update" = true ]; then
            echo
            echo "🎬 Database was updated with latest awards data!"
            echo "🧪 Test your updates: curl \"https://web-production-b8145.up.railway.app/awards?year=$latest_year\""
        fi
    else
        echo "❌ Failed to push to GitHub. Please check your connection and try again."
        exit 1
    fi
else
    echo "✅ No changes to deploy - everything is up to date!"
    echo "🌐 Live URL: https://web-production-b8145.up.railway.app"
fi